### ISSUE TITLE
alternate location for the .pre-commit-config.yml file

### ISSUE THREAD

**Issue by sean-m-sullivan** [pre-commit-ci/issues#107]
I have been trying this out on my repositories, however for all of them, we keep the config files out of the TLD. 
they are in locations such as
.github/workflow-config/.pre-commit-config.yml
what I'd like to do is be able to put it in the .github folder to keep the TLD clean, 
example being
.github/.pre-commit-config.yml

I am not seeing a way to customize this, so wondering if there is any effort to search for the config in some directories in the repo.
Also if someone can point me at the repo that does the pickup, I might be able to help contribute to the feature.

**Comment by asottile** [comment]
pre-commit.ci only works with the standard location and spelling `.pre-commit-config.yaml`

it's possible this would be a paid feature in the future, but this won't be part of the free tier (it would require some app-side configuration since the config file itself can't represent this information which I don't really want to do)

thanks for the issue nonetheless!  I recommend you adhere to convention rather than adding headaches for your contributors and every service around you by deviating from standards
