### ISSUE TITLE
Only run for PRs to default branch

### ISSUE THREAD

**Issue by tacaswell** [pre-commit-ci/issues#122]
Per https://github.com/pre-commit-ci/issues/issues/73 the CI only runs for pushes to the default branch, however it will run for PRs to other branches.

This is causing spurious failures on backport PRs (PR: https://github.com/matplotlib/matplotlib/pull/22981 CI: https://results.pre-commit.ci/run/github/1385122/1651720338.WgsTx1opStW_Vd7E04EGfw) because we have not backported the precommit config to our maintenance branch.

**Comment by asottile** [comment]
this was an intentional change in the early stages of pre-commit.ci

it originally worked the way you described but users were surprised by it not running on all PRs

I'd recommend you fix your maintenance branches instead

**Comment by tacaswell** [comment]
I am not enthusiastic about backporting a null configuration file to the maintenance branch (because on the main branch we also fixed a whole bunch of spelling / style / etc that we are not going to backport).

Could you skip pushing the GH status updates in the special case of a missing configuration file?

**Comment by asottile** [comment]
that's not what I'm suggesting at all, I'm recommending fixing the lint config on the back port branch (you wouldn't just disable your testsuite I assume?) . unless I'm misunderstanding something -- for example we usually back port fixes to infra for pytest for example

I can't silently pass without a config for free tier sadly, it is meant as a deterrent for misconfiguring CI since I still have to pay for all of the invocations

**Comment by asottile** [comment]
oh I see you don't have a config at all on old branches. you can use a trivial config `repos: []`
