### ISSUE TITLE
Option to disable linking of auto-updated modules

### ISSUE THREAD

**Issue by tykeal** [pre-commit-ci/issues#145]
I'm always having to fix the auto update PRs because my projects all require commit message bodies to be less than 80 (actually 72) characters per line. Auto-update commit messages always do a markdown link to the change differences between old and new hook versions. This always blows the line length. As such, there should be a way to disable the markdown that the bot is adding.

**Comment by asottile** [comment]
I don't want to do this -- you'll probably want to just exclude these commits

**Comment by tykeal** [comment]
Just an option? Default to having it on for those that like it? I work on a lot of projects that have strict requirements on commit message structure and the auto-update PRs from the bot consistently fail because of this and what's happening in #144 which means that some human (generally me) then has to go and either modify the PR, or re-create it and close the PR that was raised.

We really like the auto-update functionality but this is a sticking point.

**Comment by asottile** [comment]
I'm sorry but I can't add flags and complexity for free -- I hope you understand.  if this were a paid plan I could rationalize investing in such a feature but for the the whims of an individual I cannot.

I recommend you configure whatever tooling you've set up to exclude these commits -- since it is certainly a false positive

**Comment by tykeal** [comment]
Fair enough, and yes I do understand.
