### ISSUE TITLE
Feature request: schedule for autoupdater

### ISSUE THREAD

**Issue by hugovk** [pre-commit-ci/issues#23]
Nice to see the autoupdater PRs coming in!

What's the schedule for these? It'd be nice to be able to set some schedule, for example monthly (or less?) is probably enough for me because the pinning works so well.

**Comment by asottile** [comment]
it's currently monday, weekly -- sorry for the out-of-band PR today yours had some problems and I was debugging on stream (turns out `prettier` breaks the autoupdater in aws)

**Comment by asottile** [comment]
I also can't really accept arbitrary scheduling since it could be problematic -- I think at most it'll be weekly or monthly, though it's actually detrimental to cost to schedule them less often since the spread of versions decreases cache efficiency

**Comment by davidism** [comment]
I'd like to be able to set monthly as well, it can be too noisy with too few changes otherwise. Since the same config is used by 7 repositories in Pallets, we get 7 notifications every Monday, often only changing one repo and often only for a bugfix release that doesn't affect us. I have Dependabot set to monthly for the same reason.

**Comment by asottile** [comment]
this is now implemented, you can set `ci: autoupdate_schedule: ...` to either `weekly` (the default), `monthly`, or `quarterly`
