### ISSUE TITLE
Add links to changelogs in autoupdater pull requests.

### ISSUE THREAD

**Issue by domdfcoding** [pre-commit-ci/issues#32]
If the hook repository provides a `CHANGELOG.md` file, it would be handy if a link to it could be provided in the pull request body.

For instance, for `pre-commit/pre-commit-hooks` the link would be https://github.com/pre-commit/pre-commit-hooks/blob/master/CHANGELOG.md

**Comment by bastienboutonnet** [comment]
I was just going to suggest that. Would be super nice if that was possible indeed.

**Comment by asottile** [comment]
repositories are treated opaquely (autoupdate doesn't know what vcs service it is, doesn't know what it was before, etc.) and changelogs are conventional-at-best (you don't really know where they are, it could be `CHANGELOG.md`, it could be the releases tab, it could be `docs/changes.rst`, etc. etc.)

I don't think this is doable in the general case, and will necessarily introduce more api calls which makes this more expensive to run -- what are your thoughts?

**Comment by bastienboutonnet** [comment]
Yeah it's definitely not straightforward... I wonder how apps like dependabot do it. Sometimes they provide info sometimes they don't and I think they just say if they can't get any info.

I would say maybe it's "cute" to at least populate the PR description with some message. It always "shocks" me a bit that there is no lovely message in the description 🐻 

But yeah other than looking into how dependabot does it I wouldn't have any suggestions and if it's a pain in the ass because it adds complication maybe there is no rush.

Just thinking that maybe when people do use it in the enterprise offering they might "demand" some PR info of at least what was changed but you're the judge of where you want to put the limits.

**Comment by janosh** [comment]
> I would say maybe it's "cute" to at least populate the PR description with some message. It always "shocks" me a bit that there is no lovely message in the description 🐻

Was about to suggest that in a new issue. Just a quick overview of changes would make sense:

```
isort 5.7.0 -> 5.8.0
flake8 2.10.0 -> 2.11.0
```

**Comment by asottile** [comment]
this is now implemented -- the next autoupdate you get will look something like this:

___

updates:
- [github.com/pre-commit/pre-commit-hooks: v3.2.0 → v3.4.0](https://github.com/pre-commit/pre-commit-hooks/compare/v3.2.0...v3.4.0)

**Comment by janosh** [comment]
Good stuff!
