### ISSUE TITLE
a way to disable certain pre-commit hooks on pre-commit.ci

### ISSUE THREAD

**Issue by graingert** [pre-commit-ci/issues#7]
I currently run https://github.com/mgedmin/check-manifest as a pre-commit hook, and it accesses the internet as part of the build, and so cannot run on the pre-commit.ci free tier

I want a way to skip those sorts of hooks, and run them on github-actions instead

**Comment by asottile** [comment]
would this solve your issue:

make pre-commit.ci run with `--hook-stage [manual]` and then you can disable hooks with `stages: [commit]`

**Comment by graingert** [comment]
@asottile I don't think so, as I want to run the hook on GitHub actions

**Comment by asottile** [comment]
are you sure? github actions can run `--hook-stage commit` (it already does)

**Comment by mfocko** [comment]
Hi, we're trying to integrate the pre-commit CI into our projects (pioneer [ogr](https://github.com/packit/ogr)). We have a quite specific test suite that has a clean up hook for the data in the pre-commit. I was trying to follow:

> would this solve your issue:
> 
> make pre-commit.ci run with `--hook-stage [manual]` and then you can disable hooks with `stages: [commit]`

and based on the web page and settings for integration on GitHub, I couldn't find the option to run CI in `manual`, so if I understand correctly, that's a future plan for you? Thanks for response :)

**Comment by asottile** [comment]
yeah no changes have been made as a result of this issue yet so the stage isn't configurable and things aren't disableable

just because I'm curious -- do you know why your particular hooks are incompatible?  do they need network? are they dependent on system tools?

**Comment by mfocko** [comment]
> yeah no changes have been made as a result of this issue yet so the stage isn't configurable and things aren't disableable
> 
> just because I'm curious -- do you know why your particular hooks are incompatible? do they need network? are they dependent on system tools?

we wanted to turn it off since it processes the test data (quite a large amount of YAMLs; it takes some time locally too) and it timed out

speaking of the time out, the hook changes the YAMLs on the go and after it was killed, the pre-commit pushed the current (shall we say work-in-progress) state of the repo, I'd say it would be probably safer to not push changes when it time outs (it resulted in missing data for the tests)

---
related PR: https://github.com/packit/ogr/pull/497
related pre-commit CI check: https://results.pre-commit.ci/run/github/161636700/1606468617.l81vSVsDQZ2GRtV8gVixNQ

**Comment by asottile** [comment]
I agree it shouldn't but also there's a bug in your hook if interruption can leave the repository in a broken state

additionally, pre-commit hooks aren't really designed to be long-running generation as you're doing, they're intended to be fast sanity checks / quick formatting -- I'd recommend moving your slow hook to a test independent

I'll open a separate issue for the timeout though

**Comment by asottile** [comment]
Here's the link to the timeout issue: https://github.com/pre-commit-ci/issues/issues/28

**Comment by Cielquan** [comment]
I think an additional setting in `.pre-commit-config.yaml` like `ci-skip-hooks: []` would be nice. `pre-commit` itself, as the name suggests, would ignore it of cause. I think the implementation could be fairly easy as the list could be put into the `SKIP` envvar, which pre-commit uses anyway.

**Comment by asottile** [comment]
A better design that I'm thinking about is a top level `ci:` mapping -- that way pre-commit does not need to be updated repeatedly to allowlist more and more options as they get added

**Comment by lachmanfrantisek** [comment]
What about some flag for each hook? e.g.: `ci: true` / `ci: false` / `skip_on_ci: true` /  ...
It feels very natural to me to have this information near the hook setup.

The question will be what is a good default, if true or false. Maybe to run all to show some results without any config change.

But the allowlist is fine as well.

@asottile Thanks for your work!

**Comment by asottile** [comment]
yeah no that's not going to work for the same reason I just stated:

> that way pre-commit does not need to be updated repeatedly to allowlist more and more options as they get added

**Comment by nijel** [comment]
Just ended up here after trying pre-commit.ci for https://github.com/WeblateOrg/weblate/

> just because I'm curious -- do you know why your particular hooks are incompatible? do they need network? are they dependent on system tools?

For us, there would be following reasons, both might have a better solution, but for now, skipping the problematic hooks seems like the easiest path:

* We use pip installed tools to be able to pin plugins and get auto-updates for these via @dependabot. I understand why it was rejected in https://github.com/pre-commit/pre-commit/issues/1351, but without pinning we get hard to track failures when some plugin changes behaviour, and it breaks some checks sometimes later due to pre-commit caching. With pinning, we would have to upgrade these manually or invent our tooling for that... This might be in the future addressed by https://github.com/pre-commit-ci/issues/issues/13, but for now, skipping such hooks seems easier.
* Our code base is big and flake8 timeouts on pre-commit.ci (tested when not using system tools, see https://github.com/WeblateOrg/weblate/pull/5311). 

We might purchase the paid plan once it is available and affordable for us, given it will address our issues.

**Comment by asottile** [comment]
You can now skip particular hooks using the brand new `skip` option in the configuration.

For example:

```yaml
ci:
    skip: [pylint]

# ...
```

this is documented [here](https://pre-commit.ci/#configuration-skip)

thanks again for the issue

**Comment by nijel** [comment]
Thanks! It works nicely for us: https://results.pre-commit.ci/run/github/3559019/1612852300.G8uJkzeuTBOM2j6wMu2OTw

**Comment by asottile** [comment]
awesome -- once I get some funding in place I'll be doubling the instance size which should get it to where your flake8 execution squeezes under the limit

I also have a performance hack that'll improve flake8's performance by about ~10-15% which might help too

also you probably don't need `flake8-isort` since you're using `isort`, you can probably swap `flake8-breakpoint` for the [`debug-statements`](https://github.com/pre-commit/pre-commit-hooks#debug-statements) hook, `flake8-no-u-prefixed-strings` isn't doing anything for you since `pyupgrade` should fix those already, `flake8-string-format` is obsoleted by the latest pyflakes + the autofixing from `pyupgrade` as well -- reducing plugins can improve your performance a little bit

**Comment by nijel** [comment]
Thanks for the suggestions. Historically, we were using just standalone flake8 and that's from where the list of plugins comes from. Later we've added pre-commit and code formatters which do fix many things checked by flake8 (we do have flake8-black as well). The main reason was to give contributors who do not run pre-commit on their code (for example by editing on GitHub) at least some feedback what might be wrong because pre-commit itself in most cases just lists changed files. With pull requests fixing things from pre-commit.ci it's probably time to remove these duplicated checks.

As for funding, I did a little bit of that just now ;-).
