### ISSUE TITLE
Ensure tier limits are documented somewhere

### ISSUE THREAD

**Issue by remi-gelinas** [pre-commit-ci/issues#99]
Hi there! I'm attempting to run CI on my cluster config repo [here](https://github.com/remi-gelinas/home-k8s), and I've tried multiple tiers (free, basic, and premium personal), but specifically the jsonnet hook seems to be too large still for the tier (a 200Mb repo according to the error).

Is there somewhere that the hook size limits are documented so that I know what tier I will need to run my hooks? Or alternatively, if pre-commit ci cannot handle this large of a hook yet, is there an alternative I can use for the meantime?

**Comment by asottile** [comment]
I can probably bump the limits a bit, I think jsonnet should probably fit if I up the repo limit -- I'll play around with stuff and let you know.

just a heads up, I haven't actually changed per-tier limits yet (and I don't _quite_ want to publicly document them since it potentially gives people abuse-information and it makes them more fiddly to change) but I'll see what I can do here!

**Comment by asottile** [comment]
yep -- looks like if I bump the limit up a bit this fits pretty nicely and isn't a big deal:

```
https://github.com/google/go-jsonnet@b10eae7c683a26fad7f7fe53f9772c806f81a0b0 (98.3MiB) (cloned)
  sha: b10eae7c683a26fad7f7fe53f9772c806f81a0b0
  envs:
  - golang@default (31.1MiB) (built)
```

**Comment by asottile** [comment]
alrighty your repo should be good to go now -- thanks again for the issue!

here's an example of me running it through a fork: https://results-dev.pre-commit.ci/run/github/428454706/1637021414.RLi7TqAiSg6LUd2m50JNfw
